/**
 * Paper Actions
 * 
 * Pre-defined actions for working with academic papers:
 * - Summarize paper
 * - Extract key findings
 * - Explain selected text
 * - Generate citation
 * - Save response as Zotero note
 */

var ZoteroAIAssistant = ZoteroAIAssistant || {};

ZoteroAIAssistant.PaperActions = {
  // Action prompts
  PROMPTS: {
    summarize: `Please provide a comprehensive summary of this paper. Include:

1. **Main Objective**: What problem does this paper address?
2. **Methodology**: What approach or methods were used?
3. **Key Findings**: What are the main results?
4. **Conclusions**: What do the authors conclude?
5. **Significance**: Why is this work important?

Keep the summary concise but thorough (around 300-400 words).`,
    
    keyFindings: `Extract and list the 5-7 most important findings or contributions from this paper. For each finding:
- State the finding clearly
- Explain its significance
- Note any limitations mentioned

Format as a numbered list.`,
    
    explain: (text) => `Please explain the following passage from the paper in clear, accessible language:

"${text}"

Include:
1. What this passage means in simple terms
2. Why it's important in the context of the paper
3. Any technical terms that need clarification`,
    
    methodology: `Describe the research methodology used in this paper:

1. **Research Design**: What type of study is this?
2. **Data Collection**: How was data gathered?
3. **Analysis Methods**: How was data analyzed?
4. **Limitations**: What limitations do the authors acknowledge?`,
    
    implications: `What are the practical implications of this paper's findings? Consider:

1. **For Researchers**: How does this advance the field?
2. **For Practitioners**: How can these findings be applied?
3. **Future Directions**: What questions remain open?`,
    
    critique: `Provide a brief critical analysis of this paper:

1. **Strengths**: What does this paper do well?
2. **Weaknesses**: What could be improved?
3. **Gaps**: What's missing or not addressed?
4. **Overall Assessment**: How significant is this contribution?`
  },

  getTaskForAction(actionName) {
    const map = {
      summarize: "summarize",
      keyFindings: "keypoints",
      methodology: "methods",
      implications: "findings",
      critique: "findings"
    };
    return map[actionName] || null;
  },
  
  /**
   * Summarize a paper
   * @param {Zotero.Item} item - The paper item
   * @param {function} onChunk - Streaming callback
   */
  async summarize(item, onChunk) {
    return await this.executeAction("summarize", item, onChunk);
  },
  
  /**
   * Extract key findings
   */
  async keyFindings(item, onChunk) {
    return await this.executeAction("keyFindings", item, onChunk);
  },
  
  /**
   * Extract key points (alias for keyFindings)
   */
  async keyPoints(item, onChunk) {
    return await this.executeAction("keyFindings", item, onChunk);
  },
  
  /**
   * Explain selected text
   */
  async explain(item, selectedText, onChunk) {
    const prompt = this.PROMPTS.explain(selectedText);
    return await ZoteroAIAssistant.ChatManager.sendMessage(prompt, {
      item,
      selectedText,
      onChunk,
      task: "explain"
    });
  },
  
  /**
   * Describe methodology
   */
  async methodology(item, onChunk) {
    return await this.executeAction("methodology", item, onChunk);
  },
  
  /**
   * Discuss implications
   */
  async implications(item, onChunk) {
    return await this.executeAction("implications", item, onChunk);
  },
  
  /**
   * Critical analysis
   */
  async critique(item, onChunk) {
    return await this.executeAction("critique", item, onChunk);
  },
  
  /**
   * Execute a predefined action
   */
  async executeAction(actionName, item, onChunk) {
    const prompt = this.PROMPTS[actionName];
    
    if (!prompt) {
      throw new Error(`Unknown action: ${actionName}`);
    }
    
    return await ZoteroAIAssistant.ChatManager.sendMessage(prompt, {
      item,
      onChunk,
      task: this.getTaskForAction(actionName)
    });
  },
  
  /**
   * Save AI response as a Zotero note
   * @param {Zotero.Item} parentItem - The paper item
   * @param {string} content - The note content
   * @param {string} title - Note title prefix
   */
  async saveAsNote(parentItem, content, title = "AI Analysis") {
    try {
      const note = new Zotero.Item("note");
      note.parentID = parentItem.id;
      note.libraryID = parentItem.libraryID;
      
      // Format note content
      const timestamp = new Date().toLocaleString();
      const provider = Zotero.Prefs.get("extensions.zotero-ai-assistant.defaultProvider", true);
      const model = Zotero.Prefs.get("extensions.zotero-ai-assistant.defaultModel", true);
      
      const noteHTML = `
        <h1>${title}</h1>
        <p><em>Generated by Zotero AI Assistant on ${timestamp}</em></p>
        <p><em>Model: ${model} (${provider})</em></p>
        <hr/>
        ${this.markdownToHTML(content)}
      `;
      
      note.setNote(noteHTML);
      await note.saveTx();
      
      Zotero.debug("ZoteroAIAssistant.PaperActions: Saved note " + note.id);
      
      return note;
    } catch (error) {
      Zotero.debug("ZoteroAIAssistant.PaperActions: Failed to save note: " + error);
      throw error;
    }
  },
  
  /**
   * Convert markdown to HTML (basic implementation)
   */
  markdownToHTML(markdown) {
    if (!markdown) return "";
    
    let html = markdown
      // Escape HTML
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      // Headers
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      // Bold
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      // Italic
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      // Code blocks
      .replace(/```(\w*)\n([\s\S]*?)```/g, "<pre><code>$2</code></pre>")
      // Inline code
      .replace(/`(.+?)`/g, "<code>$1</code>")
      // Lists
      .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
      .replace(/^- (.+)$/gm, "<li>$1</li>")
      // Paragraphs
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br/>");
    
    // Wrap in paragraph
    html = "<p>" + html + "</p>";
    
    // Fix list items
    html = html.replace(/(<li>.*?<\/li>)+/g, (match) => "<ul>" + match + "</ul>");
    
    return html;
  },
  
  /**
   * Generate a citation (basic implementation)
   */
  generateCitation(item, style = "apa") {
    const metadata = ZoteroAIAssistant.PDFReader.getItemMetadata(item);
    if (!metadata) return null;
    
    // Basic APA-style citation
    const authors = metadata.authors || ["Unknown"];
    const year = metadata.date ? new Date(metadata.date).getFullYear() : "n.d.";
    const title = metadata.title || "Untitled";
    const source = metadata.publicationTitle || "";
    
    let authorStr;
    if (authors.length === 1) {
      authorStr = authors[0];
    } else if (authors.length === 2) {
      authorStr = `${authors[0]} & ${authors[1]}`;
    } else {
      authorStr = `${authors[0]} et al.`;
    }
    
    return `${authorStr} (${year}). ${title}. ${source}`.trim();
  }
};
